[project]
name = "agent-zep"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.98",
    "openai>=1.90.0",
    "zep-cloud>=2.16.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["agentuity-agents*"]
namespaces = false
