[project]
name = "sample-uv-langchain"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <=3.12"
dependencies = [
    "agentuity>=0.0.85",
    "langchain>=0.3.25",
    "langchain-anthropic>=0.3.13",
    "langchain-community>=0.3.24",
]
