[project]
name = "docs-qa-agent-py"
version = "0.1.0"
description = "Demonstrates all three Agentuity storage types with a simple Q&A agent."
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.106",
    "openai>=1.109.0",
]
