[project]
name = "sample-uv-llamaindex"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <=3.12"
dependencies = [
    "agentuity>=0.0.85",
    "llama-index==0.12.36",
    "llama-index-core==0.12.36",
    "llama-index-llms-anthropic>=0.6.14"
]
