[project]
name = "crewai-researcher"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <=3.12"
dependencies = [
    "agentuity>=0.0.91",
    "crewai>=0.121.1",
    "langchain-anthropic>=0.3.14",
]
