[project]
name = "from-agno"
version = "0.1.0"
description = "A collection of Agno example agents ported to Agentuity."
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.16",
    "openai>=1.82.0",
]
