[project]
name = "py-llamaindex"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
dependencies = [
    "agentuity>=0.0.91",
    "llama-index-core>=0.12.39",
    "llama-index-llms-openai>=0.4.1",
]
