[project]
name = "airbnb-mcp"
version = "0.1.0"
description = "Agno Airbnb MCP Agent converted to Agentuity"
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.106",
    "agno>=0.1.0",
    "groq>=0.8.0",
    "mcp>=1.0.0",
]
