[project]
name = "hello-world-py"
version = "0.1.0"
description = "A basic intro to building agents with Agentuity."
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.106",
    "openai>=1.108.2",
]
