[project]
name = "n8n-200"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.103",
    "openai>=1.100.0",
    "youtube-transcript-api>=0.6.0",
]
