[project]
name = "agno-finance-agent"
version = "0.1.0"
description = "Agno Finance Agent wrapped for Agentuity"
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.90",
    "agno",
    "yfinance",
    "openai>=1.82.1",
]
